name: Run E2E tests

on:
  workflow_call
    inputs:
      environment:
        required: true
        type: string 

jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}

  test:
    name: Cypress test
    needs: Run-tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # Restore just local node_modules and the Cypress binary archives.
      - name: Restore cached Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ github.ref }}-${{ hashFiles('**/package.json') }}

      - name: Restore cached node_modules
        id: restore-cached-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - if: ${{ steps.restore-cached-node-modules.outputs.cache-hit != 'true' }}
        name: Install dependencies as cache wasn't found
        run: npm ci

      # check the restored Cypress binary
      - name: Check binary
        run: |
          npx cypress cache path
          npx cypress cache list

      - name: Cypress tests
        uses: cypress-io/github-action@v5.1.0
        with:
          browser: chrome
          record: true
          group: chrome
        env:
          ENV: ${{ inputs.environment }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        