name: Preprod branch
on:
  push:
    branches:
      - stage
jobs:
  Install:
    uses: ./.github/workflows/install.yml
  Test-application:
    needs: Install
    uses: ./.github/workflows/devPortal.yml
    with:
      environment: preprod
    secrets: inherit
  