name: Preprod branch
on: workflow_dispatch

jobs:
  Install:
    uses: ./.github/workflows/install.yml
  Test-application:
    needs: Install
    uses: ./.github/workflows/devPortal.yml
    with:
      environment: prod
    secrets: inherit
  